package it.uniupo.simnova.views.creation;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.NumberField;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.router.Menu;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import org.vaadin.lineawesome.LineAwesomeIconUrl;

@PageTitle("PazienteT0")
@Route("pazienteT0")
@Menu(order = 12, icon = LineAwesomeIconUrl.PENCIL_RULER_SOLID)
public class PazienteT0View extends Composite<VerticalLayout> {

    public PazienteT0View() {
        HorizontalLayout layoutRow = new HorizontalLayout();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        Icon icon = new Icon();
        VerticalLayout layoutColumn2 = new VerticalLayout();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        H3 h3 = new H3();
        NumberField numberField = new NumberField();
        NumberField numberField2 = new NumberField();
        NumberField numberField3 = new NumberField();
        NumberField numberField4 = new NumberField();
        NumberField numberField5 = new NumberField();
        NumberField numberField6 = new NumberField();
        NumberField numberField7 = new NumberField();
        Checkbox checkbox = new Checkbox();
        Checkbox checkbox2 = new Checkbox();
        TextArea textArea = new TextArea();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        Button buttonPrimary = new Button();
        Paragraph textSmall = new Paragraph();
        Button buttonPrimary2 = new Button();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.setHeight("min-content");
        layoutRow2.setHeightFull();
        layoutRow.setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.getStyle().set("flex-grow", "1");
        layoutRow2.setAlignItems(Alignment.START);
        layoutRow2.setJustifyContentMode(JustifyContentMode.END);
        icon.setIcon("lumo:user");
        layoutColumn2.setWidth("100%");
        layoutColumn2.getStyle().set("flex-grow", "1");
        layoutColumn3.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.setWidth("100%");
        layoutColumn3.getStyle().set("flex-grow", "1");
        h3.setText("PARAMETRI VITALI PRINCIPALI");
        layoutColumn3.setAlignSelf(Alignment.CENTER, h3);
        h3.setWidth("max-content");
        numberField.setLabel("Number field");
        layoutColumn3.setAlignSelf(Alignment.CENTER, numberField);
        numberField.setWidth("min-content");
        numberField2.setLabel("Number field");
        layoutColumn3.setAlignSelf(Alignment.CENTER, numberField2);
        numberField2.setWidth("min-content");
        numberField3.setLabel("Number field");
        layoutColumn3.setAlignSelf(Alignment.CENTER, numberField3);
        numberField3.setWidth("min-content");
        numberField4.setLabel("Number field");
        layoutColumn3.setAlignSelf(Alignment.CENTER, numberField4);
        numberField4.setWidth("min-content");
        numberField5.setLabel("Number field");
        layoutColumn3.setAlignSelf(Alignment.CENTER, numberField5);
        numberField5.setWidth("min-content");
        numberField6.setLabel("Number field");
        layoutColumn3.setAlignSelf(Alignment.CENTER, numberField6);
        numberField6.setWidth("min-content");
        numberField7.setLabel("Number field");
        layoutColumn3.setAlignSelf(Alignment.CENTER, numberField7);
        numberField7.setWidth("min-content");
        checkbox.setLabel("Accessi venosi");
        layoutColumn3.setAlignSelf(Alignment.CENTER, checkbox);
        checkbox.setWidth("200px");
        checkbox2.setLabel("Accessi arteriosi");
        layoutColumn3.setAlignSelf(Alignment.CENTER, checkbox2);
        checkbox2.setWidth("200px");
        textArea.setLabel("MONITOR *indicare dettaglio ECG o altri parametri specifici");
        layoutColumn3.setAlignSelf(Alignment.CENTER, textArea);
        textArea.setWidth("60%");
        textArea.setHeight("100px");
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.setWidth("100%");
        layoutRow3.setHeight("min-content");
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.setWidth("100%");
        layoutRow4.setHeight("min-content");
        buttonPrimary.setText("Indietro");
        buttonPrimary.setWidth("10%");
        buttonPrimary.setHeight("50px");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        textSmall.setText("Sviluppato e creato da Alessandro Zappatore");
        layoutRow4.setAlignSelf(Alignment.CENTER, textSmall);
        textSmall.setWidth("100%");
        textSmall.getStyle().set("font-size", "var(--lumo-font-size-xs)");
        buttonPrimary2.setText("Avanti");
        buttonPrimary2.setWidth("10%");
        buttonPrimary2.setHeight("50px");
        buttonPrimary2.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        getContent().add(layoutRow);
        layoutRow.add(layoutRow2);
        layoutRow2.add(icon);
        getContent().add(layoutColumn2);
        layoutColumn2.add(layoutColumn3);
        layoutColumn3.add(h3);
        layoutColumn3.add(numberField);
        layoutColumn3.add(numberField2);
        layoutColumn3.add(numberField3);
        layoutColumn3.add(numberField4);
        layoutColumn3.add(numberField5);
        layoutColumn3.add(numberField6);
        layoutColumn3.add(numberField7);
        layoutColumn3.add(checkbox);
        layoutColumn3.add(checkbox2);
        layoutColumn3.add(textArea);
        getContent().add(layoutRow3);
        layoutRow3.add(layoutRow4);
        layoutRow4.add(buttonPrimary);
        layoutRow4.add(textSmall);
        layoutRow4.add(buttonPrimary2);
    }
}
