package it.uniupo.simnova.views.creation;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.NumberField;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.router.Menu;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import org.vaadin.lineawesome.LineAwesomeIconUrl;

@PageTitle("Tempo")
@Route("tempo")
@Menu(order = 14, icon = LineAwesomeIconUrl.PENCIL_RULER_SOLID)
public class TempoView extends Composite<VerticalLayout> {

    public TempoView() {
        HorizontalLayout layoutRow = new HorizontalLayout();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        Icon icon = new Icon();
        VerticalLayout layoutColumn2 = new VerticalLayout();
        Paragraph textMedium = new Paragraph();
        NumberField numberField = new NumberField();
        NumberField numberField2 = new NumberField();
        NumberField numberField3 = new NumberField();
        NumberField numberField4 = new NumberField();
        NumberField numberField5 = new NumberField();
        NumberField numberField6 = new NumberField();
        TextArea textArea = new TextArea();
        TextArea textArea2 = new TextArea();
        FormLayout formLayout2Col = new FormLayout();
        H3 h3 = new H3();
        H3 h32 = new H3();
        NumberField numberField7 = new NumberField();
        NumberField numberField8 = new NumberField();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        Button buttonPrimary = new Button();
        Paragraph textSmall = new Paragraph();
        Button buttonPrimary2 = new Button();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.setHeight("min-content");
        layoutRow2.setHeightFull();
        layoutRow.setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.getStyle().set("flex-grow", "1");
        layoutRow2.setAlignItems(Alignment.START);
        layoutRow2.setJustifyContentMode(JustifyContentMode.END);
        icon.setIcon("lumo:user");
        layoutColumn2.setWidth("100%");
        layoutColumn2.getStyle().set("flex-grow", "1");
        textMedium.setText(
                "Da leggere “Sono al tempo T0, con Parametri T0, se viene svolta un’azione vado al tempo Tn, conparametri Tn, se no passo al Tm con parametri Tm.” Riscrivere qua sotto i parametri inseritiprecedentemente.");
        layoutColumn2.setAlignSelf(Alignment.CENTER, textMedium);
        textMedium.setWidth("100%");
        textMedium.getStyle().set("font-size", "var(--lumo-font-size-m)");
        numberField.setLabel("Number field");
        numberField.setWidth("min-content");
        numberField2.setLabel("Number field");
        numberField2.setWidth("min-content");
        numberField3.setLabel("Number field");
        numberField3.setWidth("min-content");
        numberField4.setLabel("Number field");
        numberField4.setWidth("min-content");
        numberField5.setLabel("Number field");
        numberField5.setWidth("min-content");
        numberField6.setLabel("Number field");
        numberField6.setWidth("min-content");
        textArea.setLabel("Text area");
        textArea.setWidth("100%");
        textArea2.setLabel("AZIONE DA SVOLGERE PER PASSARE AL PROSSIMO Tn");
        textArea2.setWidth("100%");
        formLayout2Col.setWidth("100%");
        h3.setText("SI");
        h3.setWidth("max-content");
        h32.setText("NO");
        h32.setWidth("max-content");
        numberField7.setLabel("T");
        numberField7.setWidth("min-content");
        numberField8.setLabel("T");
        numberField8.setWidth("min-content");
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.setWidth("100%");
        layoutRow3.setHeight("min-content");
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.setWidth("100%");
        layoutRow4.setHeight("min-content");
        buttonPrimary.setText("Indietro");
        buttonPrimary.setWidth("10%");
        buttonPrimary.setHeight("50px");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        textSmall.setText("Sviluppato e creato da Alessandro Zappatore");
        layoutRow4.setAlignSelf(Alignment.CENTER, textSmall);
        textSmall.setWidth("100%");
        textSmall.getStyle().set("font-size", "var(--lumo-font-size-xs)");
        buttonPrimary2.setText("Avanti");
        buttonPrimary2.setWidth("10%");
        buttonPrimary2.setHeight("50px");
        buttonPrimary2.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        getContent().add(layoutRow);
        layoutRow.add(layoutRow2);
        layoutRow2.add(icon);
        getContent().add(layoutColumn2);
        layoutColumn2.add(textMedium);
        layoutColumn2.add(numberField);
        layoutColumn2.add(numberField2);
        layoutColumn2.add(numberField3);
        layoutColumn2.add(numberField4);
        layoutColumn2.add(numberField5);
        layoutColumn2.add(numberField6);
        layoutColumn2.add(textArea);
        layoutColumn2.add(textArea2);
        layoutColumn2.add(formLayout2Col);
        formLayout2Col.add(h3);
        formLayout2Col.add(h32);
        formLayout2Col.add(numberField7);
        formLayout2Col.add(numberField8);
        getContent().add(layoutRow3);
        layoutRow3.add(layoutRow4);
        layoutRow4.add(buttonPrimary);
        layoutRow4.add(textSmall);
        layoutRow4.add(buttonPrimary2);
    }
}
